# Generated by Django 4.0 on 2021-12-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_man', models.CharField(max_length=200, verbose_name='Имя производителя')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_det', models.CharField(max_length=200, verbose_name='Наименование детали')),
                ('cost_det', models.IntegerField(default=0, verbose_name='Цена детали')),
                ('mans', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Factory.manufacturers')),
            ],
        ),
    ]
